# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Kingfisher'
  pod 'ObjectMapper', '~> 2.2'
  pod 'ACProgressHUD-Swift', '~> 1.2'
  pod 'Toast', '~> 2.4'
  pod 'ReachabilitySwift'



  # Pods for MovieApp

  target 'MovieAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
